# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ruchi Tiwari
description:      'I work as User Experience Designer at Azani Sport in Bangalore.'
url:              http://ruchi.xyz
baseurl:          http://ruchi.xyz
logo:             /content/images/me.png

author:
  name:           'Ruchi Tiwari'
  url:            https://medium.com/@ruchi.tiwari

paginate:         5

disqus_shortname: ruchitiwari

github:
  repo:           https://github.com/ruchi-tiwari/ruchi-tiwari.github.io

gems:
  - jekyll-sitemap
  - jekyll-paginate

twitter: '@ruchitiwari'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  syntax_highlighter: rouge
